version: '3.3'
services:
  feelingsurf:
    network_mode: host
    container_name: feelingsurf
    environment:
      - access_token=91399d574fcad3ce98445a7a33a94175
    image: 'feelingsurf/viewer:stable'
    restart: unless-stopped
 
  # otohits:
  #   restart: unless-stopped
  #   container_name: otohits
  #   environment:
  #     - APPLICATION_KEY=d8e012e5-25f7-4610-8ec1-7d3840023312
  #   image: 'otohits/app:latest'

  traffmonetizer:
    restart: unless-stopped
    container_name: traffmonetizer
    command: start accept --token 67CtdHwXSmhAFEDYJ4OUcf4lilwIjulI3shJFqVn2MI= --device-name traffmonetizer
    image: 'traffmonetizer/cli_v2'
  
  9hits:
    container_name: 9hits
    image: 9hitste/app
    command: /nh.sh --token=ed8aa5dd67eeaac8bfe307df50a95a4c --system-session --allow-crypto=no
    network_mode: host
 
  # repocket:
  #   container_name: repocket
  #   environment:
  #     - RP_EMAIL=dukou1213@gmail.com
  #     - RP_API_KEY=ebad4050-673a-4071-8139-677ddc543bbd
  #   image: 'repocket/repocket'

  # proxylite:
  #   container_name: proxylite
  #   image: proxylite/proxyservice
  #   environment:
  #     - USER_ID=502036
  #   restart: unless-stopped